#!/usr/bin/env bash
# lib/guide-refresh-boot.sh - @reboot ONE-SHOT (generated by 46.sh).
# After a VM reboot, waits for the Jellyfin container to become HEALTHY, then
# triggers the "Refresh Guide" scheduled task ONCE so Live TV EPG data is re-primed
# (the last completed refresh otherwise predates the reboot). Jellyfin's own internal
# scheduler continues to run the regular periodic refreshes - this is boot-only.
# The API key is read from secrets/ and passed via a curl config on a private fd
# (curl -K), so it never appears in the process argv or in this log.
set -euo pipefail
export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
PROOT="$(cd -- "$(dirname -- "$0")/.." >/dev/null 2>&1 && pwd -P)"
CID="fcuk-em-all-jellyfin"
TASK_ID="bea9b218c97bbf98c5dc1303bdb9a0ca"
KEY_FILE="${PROOT}/secrets/jellyfin_api_key.txt"

log(){ printf '[%s] [guide-refresh-boot] %s\n' "$(date '+%Y-%m-%d %H:%M:%S')" "$*"; }

# Single-instance guard (@reboot fires once, but be safe against manual re-runs).
exec 9>/tmp/sf-guide-refresh-boot.lock
flock -n 9 || { log "another instance holds the lock; skip"; exit 0; }

[ -s "$KEY_FILE" ] || { log "ERROR: jellyfin api key file missing/empty: $KEY_FILE"; exit 1; }

# Wait until the Jellyfin docker healthcheck reports 'healthy' (up to 10 min).
DEADLINE=$(( $(date +%s) + 600 ))
while :; do
  STATUS="$(docker inspect -f '{{.State.Health.Status}}' "$CID" 2>/dev/null || true)"
  [ "$STATUS" = "healthy" ] && break
  if [ "$(date +%s)" -ge "$DEADLINE" ]; then
    log "ERROR: ${CID} not healthy within 600s (last status: '${STATUS:-unknown}'); aborting"
    exit 1
  fi
  log "waiting for ${CID} to become healthy (status: '${STATUS:-starting}')..."
  sleep 10
done
log "${CID} healthy; triggering Refresh Guide (task ${TASK_ID})"

JF_IP="$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' "$CID" 2>/dev/null || true)"
[ -n "$JF_IP" ] || { log "ERROR: could not resolve ${CID} IP on the docker network"; exit 1; }

# curl -K reads the auth header from a config on process substitution (private fd) so
# the API key is never on the argv. printf is a bash builtin -> no ps exposure either.
CODE="$(curl -s -o /dev/null -w '%{http_code}' --max-time 30 -X POST \
  -K <(printf 'header = "X-Emby-Token: %s"\n' "$(cat "$KEY_FILE")") \
  "http://${JF_IP}:8096/ScheduledTasks/Running/${TASK_ID}")"

case "$CODE" in
  200|204) log "SUCCESS: Refresh Guide triggered (HTTP ${CODE})"; exit 0 ;;
  *)       log "ERROR: trigger failed (HTTP ${CODE})"; exit 1 ;;
esac
