#!/usr/bin/env bash
# lib/importer-run.sh - cron wrapper for the FCUK-EM-ALL importer (generated by 29.sh).
# flock so overlapping sweeps cannot race; one throwaway container per sweep.
set -euo pipefail
export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
PROOT="$(cd -- "$(dirname -- "$0")/.." >/dev/null 2>&1 && pwd -P)"
exec 9>/tmp/sf-importer.lock
flock -n 9 || { echo "[importer-run] previous sweep still running; skip"; exit 0; }
exec docker run --rm --network fcuk-em-all \
  -e SF_QUIET_SECONDS="${SF_QUIET_SECONDS:-30}" ${SF_DRY_RUN:+-e SF_DRY_RUN=1} \
  -v /srv/media:/srv/media \
  -v "${PROOT}/secrets:/run/secrets:ro" \
  -v "${PROOT}/sample-media:/manifests" \
  -v "${PROOT}/lib/importer.py:/importer.py:ro" \
  "fcuk-em-all/importer:local"
