#!/usr/bin/env bash
# lib/prune-run.sh - daily auto-prune wrapper (generated by 31.sh).
# Rescans every app + Jellyfin path-based phantom deletion (SF_PRUNE) so items
# whose backing files were deleted self-heal out of the libraries. SHARES the
# importer's lock with flock -w (WAIT for any in-flight sweep / other prune;
# never run concurrently) so it cannot race the 60s importer sweep.
set -euo pipefail
export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
PROOT="$(cd -- "$(dirname -- "$0")/.." >/dev/null 2>&1 && pwd -P)"
exec 9>/tmp/sf-importer.lock
flock -w 300 9 || { echo "[prune-run] could not acquire lock within 300s; skip"; exit 0; }
docker run --rm --network fcuk-em-all -e SF_PRUNE=1 \
  -v /srv/media:/srv/media \
  -v "${PROOT}/secrets:/run/secrets:ro" \
  -v "${PROOT}/lib/importer.py:/importer.py:ro" \
  "fcuk-em-all/importer:local" || echo "[prune-run] prune returned non-zero (continuing to storage guardrail)"

# --- storage guardrail (33.sh): visibility-only; WARN if /srv/media exceeds the
# threshold (default 80%). NO automatic deletion of user content - just a clear
# line in prune-cron.log so a filling disk is noticed before it bites.
THRESH="${SF_DISK_THRESHOLD:-80}"
USE="$(df -P /srv/media 2>/dev/null | awk 'NR==2{gsub("%","",$5); print $5}')"
AVAIL="$(df -Ph /srv/media 2>/dev/null | awk 'NR==2{print $4}')"
if [ "${USE:-0}" -ge "${THRESH}" ]; then
  echo "[prune-run] WARNING: /srv/media at ${USE}% used (avail ${AVAIL}) - exceeds ${THRESH}% guardrail. No auto-deletion; free space or expand storage."
else
  echo "[prune-run] storage OK: /srv/media at ${USE}% used (avail ${AVAIL}, threshold ${THRESH}%)."
fi
